services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - user

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "4001:4001"

  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    ports:
      - "4002:4002"
